name: Publish in GitHub Package Registry

on:
  push:
    tags:
      - '*'      

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Cache NuGet
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-main-${{ hashFiles('src/**/Directory.Packages.props', 'src/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-nuget-main-

    - name: Restore packages
      run: dotnet nuget update source github --configfile ./nuget.config --username USERNAME --password ${{ secrets.GH_PACKAGES_TOKEN }} --store-password-in-clear-text
      shell: pwsh
      
    - name: Build in restore mode
      run: dotnet build /t:Restore
      working-directory: src/rNascar23.Sdk/rNascar23.Sdk
      shell: pwsh

    - name: Build
      run: dotnet build --no-restore /p:Configuration=Release
      working-directory: src/rNascar23.Sdk/rNascar23.Sdk
  
    - name: Push to GitHub Packages
      run: |
        dotnet nuget push **/*.nupkg --api-key ${{ secrets.GH_PACKAGES_TOKEN }} --source https://nuget.pkg.github.com/RRoberts4382/index.json --skip-duplicate
        
        
